//
//  main.cpp
//  interativeQuickSort
//
//  Created by syfo_dias on 12/01/2021.
//  Copyright © 2021 syfo_dias. All rights reserved.
//

#include <iostream>
#include <vector>
#include <random>
#include "quickSort.h"
#include "selectionSort.h"
#include "insertionSort.h"

// RANDOM GENERATOR
namespace random_gen
{
    /** Set a seed. */
    auto seed = std::chrono::system_clock::now().time_since_epoch().count();
    /** Initialise the generator. */
    std::mt19937 generator {static_cast<std::mt19937::result_type>(seed)};
}

// DISTRIBUTION
int getRandomInt (const int& min, const int& max)
{
    std::uniform_int_distribution<> value {min, max};
    // transforms random int generated by generator into an int in range [min, max]
    return value (random_gen::generator);
}

// TESTS
// SPECIAL CASES

// RANDOM FILL

// PERFORMANCE TESTS

int main(int argc, const char * argv[]) {
    try {
        
    } catch (std::exception& e) {
        std::cerr << e.what() << '\n';
        return 1;
    }
    return 0;
}
