//
//  randomGenerator.h
//  interativeQuickSort
//
//  Created by syfo_dias on 26/01/2021.
//  Copyright © 2021 syfo_dias. All rights reserved.
//

#ifndef randomGenerator_h
#define randomGenerator_h
#import <random>

// RANDOM GENERATOR
namespace random_generator
{
    namespace gen
    {
        /** Set a seed. */
        auto seed = std::chrono::system_clock::now().time_since_epoch().count();
        /** Initialise the generator. */
        std::mt19937 generator {static_cast<std::mt19937::result_type>(seed)};
    }
    
    // DISTRIBUTION
    int getRandomInt (const int& min, const int& max)
    {
        std::uniform_int_distribution<> value {min, max};
        // transforms random int generated by generator into an int in range [min, max]
        return value (gen::generator);
    }
}



#endif /* randomGenerator_h */
